Repository ibexa/recipes-dev, pull requests merged in 2022-12, with the labels that each got.

#35 IBX-4037: Added Segmentation REST endpoint
  ibexa/commerce/4.3/config/routes/ibexa_segmentation.yaml
  ibexa/commerce/4.4/config/routes/ibexa_segmentation.yaml
  ibexa/experience/4.3/config/routes/ibexa_segmentation.yaml
  ibexa/experience/4.4/config/routes/ibexa_segmentation.yaml
Labels: Ready for review

#36 [ibexa/commerce] Added register configuration
  ibexa/commerce/4.3/config/packages/ibexa.yaml
  ibexa/commerce/4.4/config/packages/ibexa.yaml
Labels: QA approved

#32 IBX-4359: Added AuthorizationHeaderRESTRequestMatcher for REST
  ibexa/commerce/4.3/config/packages/security.yaml
  ibexa/commerce/4.4/config/packages/security.yaml
  ibexa/content/4.3/config/packages/security.yaml
  ibexa/content/4.4/config/packages/security.yaml
  ibexa/experience/4.3/config/packages/security.yaml
  ibexa/experience/4.4/config/packages/security.yaml
  ibexa/oss/4.3/config/packages/security.yaml
  ibexa/oss/4.4/config/packages/security.yaml
Labels: Improvement, QA approved

#31 IBX-3815: Commerce clean up
  ibexa/commerce/4.4/config/packages/commerce.yaml
  ibexa/commerce/4.4/config/packages/commerce/autogenerated/.gitkeep
  ibexa/commerce/4.4/config/packages/commerce/commerce.yaml
  ibexa/commerce/4.4/config/packages/commerce/commerce_advanced.yaml
  ibexa/commerce/4.4/config/packages/commerce/commerce_common.yaml
  ibexa/commerce/4.4/config/packages/commerce/commerce_demo.yaml
  ibexa/commerce/4.4/config/packages/commerce/commerce_parameters.yaml
  ibexa/commerce/4.4/config/packages/nelmio_solarium.yaml
  ibexa/commerce/4.4/config/packages/security.yaml
  ibexa/commerce/4.4/config/routes/ibexa_commerce.yaml
  ibexa/commerce/4.4/manifest.json
  ibexa/commerce/4.4/templates/themes/standard/full/welcome_page.html.twig
  ibexa/content/4.4/config/packages/commerce.yaml
  ibexa/content/4.4/config/packages/commerce/autogenerated/.gitkeep
  ibexa/content/4.4/config/packages/commerce/commerce.yaml
  ibexa/content/4.4/config/packages/commerce/commerce_advanced.yaml
  ibexa/content/4.4/config/packages/commerce/commerce_common.yaml
  ibexa/content/4.4/config/packages/commerce/commerce_demo.yaml
  ibexa/content/4.4/config/packages/commerce/commerce_parameters.yaml
  ibexa/content/4.4/config/packages/nelmio_solarium.yaml
  ibexa/content/4.4/config/routes/ibexa_commerce.yaml
  ibexa/content/4.4/manifest.json
  ibexa/experience/4.4/config/packages/commerce.yaml
  ibexa/experience/4.4/config/packages/commerce/autogenerated/.gitkeep
  ibexa/experience/4.4/config/packages/commerce/commerce.yaml
  ibexa/experience/4.4/config/packages/commerce/commerce_advanced.yaml
  ibexa/experience/4.4/config/packages/commerce/commerce_common.yaml
  ibexa/experience/4.4/config/packages/commerce/commerce_demo.yaml
  ibexa/experience/4.4/config/packages/commerce/commerce_parameters.yaml
  ibexa/experience/4.4/config/packages/nelmio_solarium.yaml
  ibexa/experience/4.4/config/routes/ibexa_commerce.yaml
  ibexa/experience/4.4/manifest.json
Labels: QA approved

#40 IBX-3815: Fixed compatibility layer after legacy commerce clean up
  ibexa/compatibility-layer/4.4/config/routes/deprecated/ibexa_compatibility_layer_commerce.yaml
  ibexa/compatibility-layer/4.4/config/routes/deprecated/ibexa_compatibility_layer_content.yaml
  ibexa/compatibility-layer/4.4/config/routes/deprecated/ibexa_compatibility_layer_experience.yaml
Labels: Doc needed
