Repository ibexa/recipes-dev, pull requests merged in 2022-09, with the labels that each got.

#24 [ibexa/docker] Added recipes for new branches in Docker package
  ibexa/docker/3.3/manifest.json
  ibexa/docker/4.1/manifest.json
  ibexa/docker/4.2/manifest.json
Labels: Ready for review

#22 IBX-3782: Moved AdminUI related configuration to ibexa_admin_ui.yaml
  ibexa/commerce/3.3/config/packages/ezplatform.yaml
  ibexa/commerce/3.3/config/packages/ezplatform_admin_ui.yaml
  ibexa/commerce/4.2/config/packages/ibexa.yaml
  ibexa/commerce/4.2/config/packages/ibexa_admin_ui.yaml
  ibexa/content/3.3/config/packages/ezplatform.yaml
  ibexa/content/3.3/config/packages/ezplatform_admin_ui.yaml
  ibexa/content/4.2/config/packages/ibexa.yaml
  ibexa/content/4.2/config/packages/ibexa_admin_ui.yaml
  ibexa/experience/3.3/config/packages/ezplatform.yaml
  ibexa/experience/3.3/config/packages/ezplatform_admin_ui.yaml
  ibexa/experience/4.2/config/packages/ibexa.yaml
  ibexa/experience/4.2/config/packages/ibexa_admin_ui.yaml
Labels: Bug, Ready for review

#23 [ibexa/cdp] IBX-3795: Added recipe for standalone ibexa/cdp package installation
  ibexa/cdp/3.3/config/packages/ibexa_cdp.yaml
  ibexa/cdp/3.3/config/routes/ibexa_cdp.yaml
  ibexa/cdp/3.3/manifest.json
  ibexa/cdp/4.2/config/packages/ibexa_cdp.yaml
  ibexa/cdp/4.2/config/routes/ibexa_cdp.yaml
  ibexa/cdp/4.2/manifest.json
  ibexa/commerce/3.3/config/packages/security.yaml
  ibexa/commerce/4.2/config/packages/security.yaml
  ibexa/content/3.3/config/packages/security.yaml
  ibexa/content/4.2/config/packages/security.yaml
  ibexa/experience/3.3/config/packages/security.yaml
  ibexa/experience/4.2/config/packages/security.yaml
Labels: Feature, Ready for review
