Repository ibexa/recipes-dev, pull requests merged in 2023-01, with the labels that each got.

#45 IBX-4694: Added go to storefront button in welcome page
  ibexa/commerce/4.4/assets/images/main-background.jpg
  ibexa/commerce/4.4/assets/scss/welcome-page.scss
  ibexa/commerce/4.4/templates/themes/standard/full/welcome_page.html.twig
  ibexa/commerce/4.4/translations/ibexa_welcome_page.en.xlf
  ibexa/content/4.4/assets/images/main-background.jpg
  ibexa/content/4.4/assets/scss/welcome-page.scss
  ibexa/experience/4.4/assets/images/main-background.jpg
  ibexa/experience/4.4/assets/scss/welcome-page.scss
  ibexa/oss/4.4/assets/images/main-background.jpg
  ibexa/oss/4.4/assets/scss/welcome-page.scss
Labels: QA approved, Ready for MERGE

#48 IBX-3767: Exposed default image variation handler as env variable
  ibexa/commerce/4.4/config/packages/ibexa.yaml
  ibexa/commerce/4.4/manifest.json
  ibexa/content/4.4/config/packages/ibexa.yaml
  ibexa/content/4.4/manifest.json
  ibexa/experience/4.4/config/packages/ibexa.yaml
  ibexa/experience/4.4/manifest.json
Labels: QA approved

#53 Added missing comment about crucial default `eng-GB` language under `admin_group`
  ibexa/commerce/3.3/config/packages/ezplatform_admin_ui.yaml
  ibexa/commerce/4.3/config/packages/ibexa_admin_ui.yaml
  ibexa/commerce/4.4/config/packages/ibexa_admin_ui.yaml
  ibexa/content/3.3/config/packages/ezplatform_admin_ui.yaml
  ibexa/content/4.3/config/packages/ibexa_admin_ui.yaml
  ibexa/content/4.4/config/packages/ibexa_admin_ui.yaml
  ibexa/experience/3.3/config/packages/ezplatform_admin_ui.yaml
  ibexa/experience/4.3/config/packages/ibexa_admin_ui.yaml
  ibexa/experience/4.4/config/packages/ibexa_admin_ui.yaml
  ibexa/oss/3.3/config/packages/ezplatform_admin_ui.yaml
  ibexa/oss/4.3/config/packages/ibexa_admin_ui.yaml
  ibexa/oss/4.4/config/packages/ibexa_admin_ui.yaml
Labels: Improvement, Ready for MERGE
