Repository ibexa/recipes-dev, pull requests merged in 2023-04, with the labels that each got.

#65 IBX-4956: Added Orders REST API routing
  ibexa/commerce/4.5/config/routes/ibexa_order_management.yaml
Labels: Ready for review

#63 [Fast forward] IBX-4170: Imported Corporate Account REST routing
  ibexa/commerce/4.5/config/routes/ibexa_corporate_account.yaml
  ibexa/experience/4.5/config/routes/ibexa_corporate_account.yaml
Labels: Fast-forward merge, Feature, Ready for MERGE

#68 [ibexa/cdp] IBX-5586: Provided updated configuration format
  ibexa/cdp/4.5/config/packages/ibexa_cdp.yaml
Labels: Bug, Ready for review

#67 IBX-5543: React Blocks fix error while creating bundle
  ibexa/commerce/4.5/assets/js/react.blocks.js
  ibexa/commerce/4.5/encore/ibexa.webpack.config.react.blocks.js
  ibexa/commerce/4.5/encore/webpack.config.js
  ibexa/commerce/4.5/templates/themes/standard/full/welcome_page.html.twig
  ibexa/commerce/4.5/templates/themes/standard/pagelayout.html.twig
  ibexa/experience/4.5/assets/js/react.blocks.js
  ibexa/experience/4.5/encore/ibexa.webpack.config.react.blocks.js
  ibexa/experience/4.5/encore/webpack.config.js
  ibexa/experience/4.5/templates/themes/standard/full/welcome_page.html.twig
  ibexa/experience/4.5/templates/themes/standard/pagelayout.html.twig
Labels: QA approved
