Repository ibexa/recipes-dev, pull requests merged in 2024-07, with the labels that each got.

#124 IBX-8356: Reworked JWT GraphQL firewall configuration to comply with Symfony-based authentication
  ibexa/commerce/5.0/config/packages/security.yaml
  ibexa/experience/5.0/config/packages/security.yaml
  ibexa/headless/5.0/config/packages/lexik_jwt_authentication.yaml
  ibexa/headless/5.0/config/packages/security.yaml
  ibexa/oss/5.0/config/packages/lexik_jwt_authentication.yaml
  ibexa/oss/5.0/config/packages/security.yaml
Labels: Doc needed, QA approved

#125 [TMP commit] IBX-8482: Fixed lack of JWT stateless calls recognition
  ibexa/commerce/5.0/config/packages/security.yaml
  ibexa/experience/5.0/config/packages/security.yaml
  ibexa/headless/5.0/config/packages/security.yaml
  ibexa/oss/5.0/config/packages/security.yaml
Labels: Bug, QA approved

#127 [ibexa/*] Added symfony/notifier subscriptions
  ibexa/commerce/5.0/config/packages/ibexa.yaml
  ibexa/experience/5.0/config/packages/ibexa.yaml
  ibexa/headless/5.0/config/packages/ibexa.yaml
  ibexa/oss/5.0/config/packages/ibexa.yaml
Labels: QA approved, Ready for review

#128 IBX-8324: Reworked JWT editorial bearer in page builder
  ibexa/commerce/5.0/config/packages/ibexa_page_builder.yaml
  ibexa/commerce/5.0/config/packages/security.yaml
  ibexa/experience/5.0/config/packages/ibexa_page_builder.yaml
  ibexa/experience/5.0/config/packages/security.yaml
Labels: Bug, Doc needed, Ready for review
