Repository ibexa/recipes-dev, pull requests merged in 2025-05, with the labels that each got.

#170 IBX-9916: Upgrade frontend dependencies
  ibexa/commerce/5.0/config/packages/ibexa_assets.yaml
  ibexa/commerce/5.0/encore/ibexa.webpack.config.js
  ibexa/commerce/5.0/encore/package.json
  ibexa/experience/5.0/config/packages/ibexa_assets.yaml
  ibexa/experience/5.0/encore/ibexa.webpack.config.js
  ibexa/experience/5.0/encore/package.json
  ibexa/headless/5.0/config/packages/ibexa_assets.yaml
  ibexa/headless/5.0/encore/ibexa.webpack.config.js
  ibexa/headless/5.0/encore/package.json
  ibexa/oss/5.0/config/packages/ibexa_assets.yaml
  ibexa/oss/5.0/encore/ibexa.webpack.config.js
  ibexa/oss/5.0/encore/package.json
Labels: Doc needed, QA approved

#177 IBX-9940: Removed Sass deprecations
  ibexa/commerce/5.0/assets/scss/_footer.scss
  ibexa/commerce/5.0/assets/scss/_header.scss
  ibexa/commerce/5.0/assets/scss/_main.scss
  ibexa/commerce/5.0/assets/scss/_training.scss
  ibexa/commerce/5.0/assets/scss/_tutorials.scss
  ibexa/commerce/5.0/assets/scss/welcome-page.scss
  ibexa/commerce/5.0/encore/package.json
  ibexa/experience/5.0/assets/scss/_footer.scss
  ibexa/experience/5.0/assets/scss/_header.scss
  ibexa/experience/5.0/assets/scss/_main.scss
  ibexa/experience/5.0/assets/scss/_training.scss
  ibexa/experience/5.0/assets/scss/_tutorials.scss
  ibexa/experience/5.0/assets/scss/welcome-page.scss
  ibexa/experience/5.0/encore/package.json
  ibexa/headless/5.0/assets/scss/_footer.scss
  ibexa/headless/5.0/assets/scss/_header.scss
  ibexa/headless/5.0/assets/scss/_main.scss
  ibexa/headless/5.0/assets/scss/_training.scss
  ibexa/headless/5.0/assets/scss/_tutorials.scss
  ibexa/headless/5.0/assets/scss/welcome-page.scss
  ibexa/headless/5.0/encore/package.json
  ibexa/oss/5.0/assets/scss/_footer.scss
  ibexa/oss/5.0/assets/scss/_header.scss
  ibexa/oss/5.0/assets/scss/_main.scss
  ibexa/oss/5.0/assets/scss/_training.scss
  ibexa/oss/5.0/assets/scss/_tutorials.scss
  ibexa/oss/5.0/assets/scss/welcome-page.scss
  ibexa/oss/5.0/encore/package.json
Labels: Ready for QA

#171 IBX-9939: TypeScript aliases for bundles
  ibexa/commerce/5.0/encore/custom.tsconfig.mjs
  ibexa/commerce/5.0/encore/ibexa.tsconfig.json
  ibexa/commerce/5.0/encore/ibexa.webpack.config.js
  ibexa/commerce/5.0/encore/package.json
  ibexa/commerce/5.0/manifest.json
  ibexa/experience/5.0/encore/custom.tsconfig.mjs
  ibexa/experience/5.0/encore/ibexa.tsconfig.json
  ibexa/experience/5.0/encore/ibexa.webpack.config.js
  ibexa/experience/5.0/encore/package.json
  ibexa/experience/5.0/manifest.json
  ibexa/headless/5.0/encore/custom.tsconfig.mjs
  ibexa/headless/5.0/encore/ibexa.tsconfig.json
  ibexa/headless/5.0/encore/ibexa.webpack.config.js
  ibexa/headless/5.0/encore/package.json
  ibexa/headless/5.0/manifest.json
  ibexa/oss/5.0/encore/custom.tsconfig.mjs
  ibexa/oss/5.0/encore/ibexa.tsconfig.json
  ibexa/oss/5.0/encore/ibexa.webpack.config.js
  ibexa/oss/5.0/encore/package.json
  ibexa/oss/5.0/manifest.json
Labels: Ready for review

#184 [ibexa/discounts-codes] Moved configuration to discount recipes
  ibexa/discounts-codes/4.6/config/packages/ibexa_discounts_codes.yaml
Labels: Ready for review
