Repository ibexa/recipes-dev, pull requests merged in 2025-07, with the labels that each got.

#197 IBX-9697: Added Ibexa Twig Components bundle to manifest
  ibexa/commerce/4.6/manifest.json
  ibexa/commerce/5.0/manifest.json
  ibexa/experience/4.6/manifest.json
  ibexa/experience/5.0/manifest.json
  ibexa/headless/4.6/manifest.json
  ibexa/headless/5.0/manifest.json
  ibexa/oss/4.6/manifest.json
  ibexa/oss/5.0/manifest.json
Labels: Ready for review

#202 IBX-10299: [ibexa/share] Added routing config
  ibexa/share/4.6/config/routes/ibexa_share.yaml
  ibexa/share/5.0/config/routes/ibexa_share.yaml
Labels: Ready for review

#205 IBX-10292: Commented out default league_oauth2_server configuration
  ibexa/commerce/5.0/config/packages/league_oauth2_server.yaml
  ibexa/experience/5.0/config/packages/league_oauth2_server.yaml
  ibexa/headless/5.0/config/packages/league_oauth2_server.yaml
Labels: Doc needed

#198 IBX-10231: Removed Solr parameters from configuration file
  ibexa/commerce/5.0/config/packages/ibexa_solr.yaml
  ibexa/experience/5.0/config/packages/ibexa_solr.yaml
  ibexa/headless/5.0/config/packages/ibexa_solr.yaml
  ibexa/oss/5.0/config/packages/ibexa_solr.yaml
Labels: Ready for review

#195 IBX-10261: Enabled special characters plugin in CKE
  ibexa/commerce/4.6/encore/package.json
  ibexa/experience/4.6/encore/package.json
  ibexa/headless/4.6/encore/package.json
  ibexa/oss/4.6/encore/package.json
Labels: QA approved
