Repository ibexa/recipes-dev, pull requests merged in 2025-03, with the labels that each got.

#158 IBX-9239: Added recipe for ibexa/connect package
  ibexa/connect/4.6/config/packages/ibexa_connect.yaml
  ibexa/connect/4.6/manifest.json
  ibexa/connect/5.0/config/packages/ibexa_connect.yaml
  ibexa/connect/5.0/manifest.json
Labels: Feature

#167 Fixed wrong REST endpoints path for `4.6`
  ibexa/discounts-codes/4.6/config/routes/ibexa_discounts_codes.yaml
Labels: Bug, Ready for review

#163 IBX-9711: Added discount codes applying rate limiter configuration
  ibexa/commerce/4.6/config/packages/ibexa_discounts_codes.yaml
  ibexa/commerce/5.0/config/packages/ibexa_discounts_codes.yaml
Labels: Improvement, Ready for QA
